### ISSUE TITLE
A replacement for dex2jar

### ISSUE THREAD

**Issue by nguyenvulong** [cryptax/androidre#1]
I found a tool from Google, named Enjarify, which has similar functionality like dex2jar
https://github.com/Storyyeller/enjarify

Maybe you'll want to give it a try and adopt it to your docker file

Thanks

**Comment by cryptax** [comment]
ok thanks, I'll give it a try ASAP

**Comment by cryptax** [comment]
Tested. Works quite well, I'll be pushing a new version tomorrow with Enjarify & Frida.
