### ISSUE TITLE
Android emulator is not working

### ISSUE THREAD

**Issue by yonatanhaf** [cryptax/androidre#3]
Hi, I was trying to start the Android emulator by the "quick start" steps. When I'm trying to start the emulator, by running the `emulator8x86` command, I get 

```
emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
```

What should I do in order to start the emulator?

Thanks!

**Comment by cryptax** [comment]
Hmmm. You have done this, right?:

>  Have an Intel x86 processor on your host which supports virtualization (e.g Intel VT)
>  Launch the container with the --privileged option.

**Comment by cryptax** [comment]
I've committed a new Dockerfile, and it works on my host, with the --privileged option. Check it out?
